### ISSUE TITLE
User-Agent to include site name

### ISSUE THREAD

**Issue by Regner** [eve-seat/seat#350]
Is it possible to add the name of the site to the user agent string? It currently includes pheal version and seat version: PhealNG/1.3.0+SeAT+0.13.0API+Fetcher

Would be wonderful if site name was also there to help give me an idea of who to contact if a seat install goes a bit crazy.

**Comment by freedenizen** [comment]
It is most likely me :D I have over 800 keys in there and get 904 IP blocks pretty much everyday

**Comment by eve-seat** [comment]
Definitely! We can add say `config::get('app.url')` to https://github.com/eve-seat/seat/blob/master/app/eveapi/BaseAPI.php#L62. @Regner would this help already?

**Comment by Regner** [comment]
I am mainly looking for some way to identify who owns the install so I can get in touch with them. Either EVE Mail or other. The apps URL could work, I don't know what people usually put their apps under. If it was something like seat.goonswarm.com I would know who to poke. It's probably the best thing available. :)

Much appreciated.

**Comment by eve-seat** [comment]
I think we could maybe add the default mail_from value too to help with that.

**Comment by freedenizen** [comment]
In all seriousness the current stuff you are seeing might be from mine, how can I contact you in a not public forum to send you the IP they would be originating from?

**Comment by Nutbolt52** [comment]
My default mail from address is some nonsense address which doesn't exist, so you could try and contact me there all you like but I wouldn't response :p 

I think the app URL makes the most sense because lets be honest, you would install SeAT under a meaningful address, and not something like bob.random.com. The only issue I can see with that is something like eveseat.com, who owns that for example.

**Comment by eve-seat** [comment]
@Nutbolt52 which is why both the url and mail from will be going in.

**Comment by LunarchildEU** [comment]
What about a field in the Settings or Env-file where you can enter either an Character or administrative email as alternative contact in case the 'mail_from' is not configured to receive mail.

If [url in app.php](https://github.com/eve-seat/seat/blob/master/app/config/app.php#L29) is set it might also solves something strange with the notification mails pretending to be from 'localhost'.

**Comment by Nutbolt52** [comment]
Fair play @eve-seat. As long as FoxFour doesn't try e-mailing seatadmin@myurl.com :D

**Comment by Regner** [comment]
@freedenizen You can get me at regner@ccpgames.com

**Comment by Regner** [comment]
Thanks for putting some thought and effort into this guys, really appreciate it. :)

**Comment by Nutbolt52** [comment]
Might be getting cocky, I don't know (it gets technical), but an optional setting in the SeAT Settings page, which allows you to state contact details for the user agent (where the user can set a sanitized string), so anything from ingame name, to e-mail address, to god knows what. 

IF this setting isn't set, then default back to app_url & mail. 

This might be better because lets be honest, if you are running an instance which is so big your getting limited by the API, chances are you would take the time to set some meaningful contact details.

**Comment by eve-seat** [comment]
I've added contact information to the User-Agent with 44811c71b01f. Sample User-Agents, depending on if the Administrative Contact has been set will be:

`SeAT 0.13.0 API Fetcher at http://localhost Install mail_from SeAT Administrator <seatadmin@localhost>`
and
`SeAT 0.13.0 API Fetcher at http://localhost Administrative Contact: qu1ckkkk@home.local`

An Administrative Contact will be [required](https://github.com/eve-seat/seat/blob/dev/app/services/validators/SeatSettingValidator.php#L35) once an install has been upgraded with this commit and global settings need changing.

**Comment by eve-seat** [comment]
@Regner please let me know if this will suffice. Ill then accelerate a release for this too.

**Comment by eve-seat** [comment]
Released in 0.14
