### ISSUE TITLE
Upgrading Laravel Version

### ISSUE THREAD

**Issue by mglinski** [eve-seat/seat#352]
Is there a desire to upgrade Laravel to v4.2 or v5.0 in the near future? 

Getting up to v4.2 should be very simple, going to v5 might be a bit more involved. There is a lot of simplifications that L5 will afford you guys if you want to put the time in to migrating. Route caching, synchronous command busses, built in scheduled commands, psr4 loading, etc.

I would be happy to help migrate the codebase up to v5 in the near future if there is interest. Otherwise I plan on forking the project for our internal needs if there is no interest in this upstream. 

LMK

**Comment by eve-seat** [comment]
The biggest hold back was the PHP 5.4 requirement for Laravel 4.2+. Blame the 'ol CentOS 6 machines that are technically supported, but still ship with 5.3 -_-

CentOS 7 has since been released, which 5.4+ (or whatever it has) which voids this problem. I have not looked at all of the details with L5 yet, and figured I'd wait for a few point released to get the pains out the way. So. the answer is yes, upgrading is something that should happen. I don't think Taylor is  very popular with supporting older framework versions.

I do know there is another guy that hangs out on IRC that also wants to bring in some optimizations wrt the way code could be re-used correctly for unit testing etc. I have not yet heard much from him since, but this is also something I think may affect the larger roadmap of a L5 migration.

**Comment by mglinski** [comment]
I have done 4 smaller projects with L5 now to get a feel for the new included systems and I am pretty happy with them. I'll hop in your guys IRC then and get a feel for things. In the meantime, see my unrelated PR :)

**Comment by eve-seat** [comment]
As per #359, we will definitely be moving to L5.1
