### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by stevensT** [eve-seat/seat#403]
the "Errored Jobs" is showing a very large number. When navigating to that page (*/queue/status), I do not get a return, but o dont get an error ether (404, ect.).  I can navigate to all other pages without issues

**Comment by eve-seat** [comment]
Could you attach a screenshot?

**Comment by stevensT** [comment]
[Imgur](http://i.imgur.com/yA3nTuS.jpg)
Not really sure what the issue is, I was have issues with the Linux firewall and getting a Forbidden error.  Now I can navigate to any page but this one.

**Comment by LunarchildEU** [comment]
There is possibly 2 logs you can check, one is the laravel.log and the other that one where php saves its errors (could be also the error log of the webserver)

**Comment by stevensT** [comment]
OK, I'll check those logs.  When using IE, I get a HTTP 500 error.  [More Imgur pics here](http://imgur.com/a/MRXGL), but like chrome, it is only on the /queue/status page.

**Comment by warlof** [comment]
It looks a miss config in your php.ini or apache since seat use custom error page. You got an E500 on both of your brother (use the dev tool in chrome and get in network tab)
What your php log says ?
Le 12 juil. 2015 07:36, Trevor Stevens <notifications@github.com> a écrit :OK, I'll check those logs.  When using IE, I get a HTTP 500 error.  More Imgur pics here, but like chrome, it is only on the /queue/status page.

**Comment by eve-seat** [comment]
Did this ever get sorted?
